### ISSUE TITLE
Invalid placement of language switch on Chromium browsers

### ISSUE THREAD

**Issue by QuickWrite** [hls-ol/pons-dictionary#1]
## What is the problem?

Whilst in Gecko based browsers (e.g. Firefox), the language switch is being placed correctly, the language switch is above the desired location in Chromium based browsers (e.g. Chrome, Edge, Brave):
![Example of the issue where the language switch is above the input field](https://github.com/user-attachments/assets/3624e968-0279-41e1-a26d-313e884a66b7)

## Correct behaviour

The correct behaviour can be observed in Firefox:
![The correct rendering of the language switch on the right](https://github.com/user-attachments/assets/cb36a915-3015-457d-a5b7-36b4b2ec5db8)

> [!NOTE]
> The different width of both images has nothing to do with the issue.

**Comment by djtilo-ol** [comment]
It also shows in SafeExamBrowser, which is Chrome at its heart, I believe.
